# Generated by Django 4.2.4 on 2023-08-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTelovendo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
