# Generated by Django 4.2.4 on 2023-08-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTelovendo', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
